streamlit compromise.

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -1,31 +1,31 @@
-name: Docker Build and Push
+# name: Docker Build and Push
 
-on:
-  push:
-    branches:
-      - main
+# on:
+#   push:
+#     branches:
+#       - main
 
-jobs:
-  build-and-push:
-    runs-on: ubuntu-latest
+# jobs:
+#   build-and-push:
+#     runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v2
       
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
+#       - name: Set up Docker Buildx
+#         uses: docker/setup-buildx-action@v1
       
-      - name: Log into Docker Hub
-        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+#       - name: Log into Docker Hub
+#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
 
-      - name: Build and push Docker image
-        run: |
-          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/chess-gpt"
-          docker build -t $IMAGE_NAME:latest .
-          docker push $IMAGE_NAME:latest
+#       - name: Build and push Docker image
+#         run: |
+#           IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/chess-gpt"
+#           docker build -t $IMAGE_NAME:latest .
+#           docker push $IMAGE_NAME:latest
 
-      # Handle exit codes
-      - name: Check for errors
-        if: ${{ failure() }}
-        run: exit 1
+#       # Handle exit codes
+#       - name: Check for errors
+#         if: ${{ failure() }}
+#         run: exit 1
